<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!-- Migrado para .NET 8 -->
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="13.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="9.0.6" />
	</ItemGroup>

	<ItemGroup>
		<!-- Refere a camada de domínio -->
		<ProjectReference Include="..\AuthClient.Domain\AuthClient.Domain.csproj" />
		<PackageReference Include="MediatR" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.1" />
	</ItemGroup>
</Project>
